# Generated by Django 4.2.20 on 2025-03-14 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_completed', models.IntegerField(default=0)),
                ('money_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('jobs_in_queue', models.IntegerField(default=0)),
                ('applications_pending', models.IntegerField(default=0)),
                ('hours_logged', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_posted', models.IntegerField(default=0)),
                ('jobs_open', models.IntegerField(default=0)),
                ('hired_freelancers', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_payments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issues_reported', models.IntegerField(default=0)),
                ('issues_resolved', models.IntegerField(default=0)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('access_level', models.CharField(default='standard', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
