# Generated by Django 4.2.20 on 2025-04-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
