# Generated by Django 4.2.20 on 2025-04-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_employer_rating_job_freelancer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='time_estimate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
