# Generated by Django 4.2.20 on 2025-04-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='job',
            name='freelancer_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
