apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freelance-portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bilal-khawar/Freelance-Portal-DevOps  
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: freelance-portal-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

