# Generated by Django 4.2.20 on 2025-03-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_freelancerprofile_employerprofile_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='jobs_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
