---
- name: Configure Django Server
  hosts: django
  become: true
  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install virtualenv
      pip:
        name: virtualenv
        executable: pip3

    - name: Create a virtual environment
      command: python3 -m venv /home/ubuntu/django_project/venv creates=/home/ubuntu/django_project/venv

    - name: Install dependencies from requirements.txt
      pip:
        requirements: /home/ubuntu/django_project/requirements.txt
        virtualenv: /home/ubuntu/django_project/venv

    - name: Run Django server
      command: /home/ubuntu/django_project/venv/bin/python3 /home/ubuntu/django_project/manage.py runserver 0.0.0.0:8000
