# Generated by Django 4.2.20 on 2025-04-25 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disputeresolution',
            name='dispute',
        ),
        migrations.RemoveField(
            model_name='disputeresolution',
            name='resolved_by',
        ),
        migrations.AlterField(
            model_name='dispute',
            name='dispute_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DisputeManager',
        ),
        migrations.DeleteModel(
            name='DisputeResolution',
        ),
    ]
