name: CI/CD Pipeline for Freelance Portal

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -f FreelancePortal/Dockerfile -t 22i0786/freelance-portal:latest FreelancePortal
          docker push 22i0786/freelance-portal:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          
          if [ ! -z "${{ secrets.K8S_API_SERVER }}" ]; then
            kubectl config set-cluster docker-desktop --server=${{ secrets.K8S_API_SERVER }}
          fi
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

      - name: Verify Kubernetes connection
        run: |
          echo "Displaying kubeconfig (redacted):"
          kubectl config view --minify
          
          echo "Attempting to connect to Kubernetes cluster..."
          kubectl cluster-info || true
          kubectl get nodes || echo "Failed to get nodes but continuing..."

      - name: Deploy to Kubernetes
        run: |
          echo "Setting up default namespace if not specified in YAML files"
          DEFAULT_NAMESPACE="freelance-portal"
          
          if [ -f kubernetes/namespace.yaml ]; then
            kubectl apply -f kubernetes/namespace.yaml --validate=false || echo "Namespace creation failed, continuing..."
            NAMESPACE=$(grep -o 'name: [a-zA-Z0-9-]*' kubernetes/namespace.yaml | cut -d' ' -f2 || echo "$DEFAULT_NAMESPACE")
          else
            NAMESPACE="$DEFAULT_NAMESPACE"
            kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f - --validate=false
          fi
          
          echo "Using namespace: $NAMESPACE"

          echo "Applying Kubernetes configurations..."
          if [ -f kubernetes/secrets.yaml ]; then
            kubectl apply -f kubernetes/secrets.yaml -n $NAMESPACE --validate=false || echo "Failed to apply secrets, continuing..."
          fi

          if [ -f kubernetes/configmap.yaml ]; then
            kubectl apply -f kubernetes/configmap.yaml -n $NAMESPACE --validate=false || echo "Failed to apply configmap, continuing..."
          fi

          echo "Applying deployment..."
          for i in {1..3}; do
            kubectl apply -f kubernetes/deployment.yaml -n $NAMESPACE --validate=false && break || echo "Retry $i for deployment..."
            sleep 5
          done

          if [ -f kubernetes/service.yaml ]; then
            kubectl apply -f kubernetes/service.yaml -n $NAMESPACE --validate=false || echo "Failed to apply service, continuing..."
          fi
          
          if [ -f kubernetes/ingress.yaml ]; then
            kubectl apply -f kubernetes/ingress.yaml -n $NAMESPACE --validate=false || echo "Failed to apply ingress, continuing..."
          fi
          
          echo "Deployment complete, checking deployment status (will continue regardless of status)..."
          kubectl rollout status deployment/freelance-portal -n $NAMESPACE --timeout=60s || echo "Deployment may not be ready yet, check manually."