name: CI/CD Pipeline for Freelance Portal

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/freelance-portal:latest .
          docker push your-dockerhub-username/freelance-portal:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig.yaml
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/namespace.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/secrets.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/configmap.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/deployment.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/service.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/ingress.yaml

